apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BadgerV/kubernetes-test.git
    targetRevision: master
    path: applications/nginx/helm-chart  # ✅ Path to the Helm chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-namespace  # Namespace where the Helm chart is deployed
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
